/**
 * E2E: Dashboard, API Keys, Machines, Sessions, Settings
 *
 * All tests in this file target authenticated routes. They check that the UI
 * renders the correct structure and interactive elements.
 *
 * Authentication strategy:
 *   Tests check whether they landed on a login redirect and call test.skip()
 *   when no auth fixture is available. In CI, provide a storageState file:
 *     storageState: 'e2e/.auth/user.json'
 *   generated by a global-setup script.
 *
 * Tests that require live agent data (running machine, active session) are
 * marked with test.skip and include comments about what they verify.
 */

import { test, expect } from '@playwright/test'

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Returns true if the page has been redirected to the login page,
 * meaning the test cannot proceed without an authenticated session.
 */
function isLoginRedirect(url: string): boolean {
  return url.includes('/login')
}

// ─── Dashboard overview ───────────────────────────────────────────────────────

test.describe('Dashboard overview', () => {
  test('loads the Overview heading and stat cards', async ({ page }) => {
    await page.goto('/dashboard')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }

    await expect(page.getByRole('heading', { name: 'Overview' })).toBeVisible()

    // Four stat cards are always present regardless of data
    await expect(page.getByText('Total Machines')).toBeVisible()
    await expect(page.getByText('Online Now')).toBeVisible()
    await expect(page.getByText('Active Sessions')).toBeVisible()
    await expect(page.getByText('Plan')).toBeVisible()
  })

  test('sidebar navigation links are all present', async ({ page }) => {
    await page.goto('/dashboard')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }

    // Sidebar nav items from Sidebar.tsx
    await expect(page.getByRole('link', { name: 'Dashboard', exact: true })).toBeVisible()
    await expect(page.getByRole('link', { name: 'Machines', exact: true })).toBeVisible()
    await expect(page.getByRole('link', { name: 'Sessions', exact: true })).toBeVisible()
    await expect(page.getByRole('link', { name: 'API Keys', exact: true })).toBeVisible()
    await expect(page.getByRole('link', { name: 'Settings', exact: true })).toBeVisible()
  })

  test('WebSocket status indicator is present in sidebar', async ({ page }) => {
    await page.goto('/dashboard')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    // The sidebar renders "Live status:" text next to the WS indicator dot
    await expect(page.getByText('Live status:')).toBeVisible()
  })

  test.skip('WebSocket status shows "connected" when WS handshake succeeds', async ({ page }) => {
    // Requires a live server with working WebSocket support.
    // await page.goto('/dashboard')
    // await expect(page.getByText('connected')).toBeVisible({ timeout: 15_000 })
  })

  test('"New Session" button is visible on the dashboard', async ({ page }) => {
    await page.goto('/dashboard')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await expect(page.getByRole('link', { name: 'New Session' })).toBeVisible()
  })

  test('Plan Usage section is visible for free plan users', async ({ page }) => {
    await page.goto('/dashboard')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    // The "Plan Usage" card only renders when limits.machines !== -1 (i.e. free/pro)
    // For a free account this section should be visible
    await expect(page.getByText('Plan Usage')).toBeVisible()
  })
})

// ─── API Keys page ────────────────────────────────────────────────────────────

test.describe('API Keys page', () => {
  test('loads the API Keys heading', async ({ page }) => {
    await page.goto('/keys')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await expect(page.getByRole('heading', { name: 'API Keys' })).toBeVisible()
  })

  test('"Create API Key" button is visible', async ({ page }) => {
    await page.goto('/keys')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await expect(page.getByRole('button', { name: 'Create API Key' })).toBeVisible()
  })

  test('security notice is visible', async ({ page }) => {
    await page.goto('/keys')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await expect(page.getByText(/API keys grant full access/i)).toBeVisible()
  })

  test('clicking "Create API Key" opens the dialog', async ({ page }) => {
    await page.goto('/keys')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await page.getByRole('button', { name: 'Create API Key' }).click()
    // Dialog title from DialogTitle in keys/page.tsx
    await expect(page.getByRole('dialog')).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Create API Key' })).toBeVisible()
  })

  test('create key dialog has "Key Name" input and "Generate Key" button', async ({ page }) => {
    await page.goto('/keys')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await page.getByRole('button', { name: 'Create API Key' }).click()
    await expect(page.getByLabel('Key Name')).toBeVisible()
    await expect(page.getByRole('button', { name: 'Generate Key' })).toBeVisible()
  })

  test('create key dialog can be cancelled', async ({ page }) => {
    await page.goto('/keys')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await page.getByRole('button', { name: 'Create API Key' }).click()
    await page.getByRole('button', { name: 'Cancel' }).click()
    await expect(page.getByRole('dialog')).not.toBeVisible()
  })

  test.skip('generated key is shown once with sf_live_ prefix', async ({ page }) => {
    // Requires live /api/keys POST endpoint.
    // await page.goto('/keys')
    // await page.getByRole('button', { name: 'Create API Key' }).click()
    // await page.getByLabel('Key Name').fill('E2E Test Key')
    // await page.getByRole('button', { name: 'Generate Key' }).click()
    // The new-key panel renders the full key in a <code> element
    // await expect(page.locator('code').filter({ hasText: 'sf_live_' })).toBeVisible()
    // await expect(page.getByText('Your API Key — Copy now!')).toBeVisible()
  })

  test.skip('key appears in the list with sf_live_ prefix (truncated) after creation', async ({ page }) => {
    // After creating a key and closing the dialog:
    // await expect(page.getByText(/sf_live_/)).toBeVisible()
  })

  test.skip('revoke key dialog confirms and removes key from list', async ({ page }) => {
    // Requires at least one key to exist.
    // Click the trash icon on a key row → revoke dialog opens
    // await page.getByRole('button', { name: 'Revoke Key' }).click()
    // Key should disappear from the list
  })
})

// ─── Machines page ────────────────────────────────────────────────────────────

test.describe('Machines page', () => {
  test('loads the Machines heading', async ({ page }) => {
    await page.goto('/machines')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await expect(page.getByRole('heading', { name: 'Machines' })).toBeVisible()
  })

  test('"Add Machine" button is visible', async ({ page }) => {
    await page.goto('/machines')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await expect(page.getByRole('button', { name: 'Add Machine' })).toBeVisible()
  })

  test('filter tabs All / Online / Offline / Error are visible', async ({ page }) => {
    await page.goto('/machines')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await expect(page.getByRole('button', { name: /^All/ })).toBeVisible()
    await expect(page.getByRole('button', { name: /^Online/ })).toBeVisible()
    await expect(page.getByRole('button', { name: /^Offline/ })).toBeVisible()
    await expect(page.getByRole('button', { name: /^Error/ })).toBeVisible()
  })

  test('clicking "Add Machine" opens the setup wizard dialog', async ({ page }) => {
    await page.goto('/machines')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await page.getByRole('button', { name: 'Add Machine' }).click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Add a New Machine' })).toBeVisible()
  })

  test('setup wizard dialog shows install command and OS tabs', async ({ page }) => {
    await page.goto('/machines')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await page.getByRole('button', { name: 'Add Machine' }).click()
    // MachineSetupWizard renders Linux/macOS/Windows tabs
    await expect(page.getByRole('button', { name: 'Linux' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'macOS' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Windows' })).toBeVisible()
    // Install command block (curl command for Linux)
    await expect(page.getByText(/curl -fsSL/)).toBeVisible()
  })

  test.skip('machine detail page loads with CPU/memory/disk cards', async ({ page }) => {
    // Requires at least one registered machine.
    // Navigate to /machines/<id> where <id> comes from the machine list.
    // await expect(page.getByText('CPU')).toBeVisible()
    // await expect(page.getByText('Memory')).toBeVisible()
    // await expect(page.getByText('Disk')).toBeVisible()
    // await expect(page.getByText('Last Seen')).toBeVisible()
  })

  test.skip('machine detail page shows Sessions and Setup tabs', async ({ page }) => {
    // Requires a registered machine ID.
    // await expect(page.getByRole('tab', { name: /Sessions/ })).toBeVisible()
    // await expect(page.getByRole('tab', { name: 'Setup' })).toBeVisible()
  })
})

// ─── Sessions page ────────────────────────────────────────────────────────────

test.describe('Sessions page', () => {
  test('loads the Sessions heading', async ({ page }) => {
    await page.goto('/sessions')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await expect(page.getByRole('heading', { name: 'Sessions' })).toBeVisible()
  })

  test('"Start Session" button is visible', async ({ page }) => {
    await page.goto('/sessions')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await expect(page.getByRole('button', { name: 'Start Session' })).toBeVisible()
  })

  test('status filter tabs are visible', async ({ page }) => {
    await page.goto('/sessions')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await expect(page.getByRole('button', { name: /^All/ })).toBeVisible()
    await expect(page.getByRole('button', { name: /^Running/ })).toBeVisible()
    await expect(page.getByRole('button', { name: /^Stopped/ })).toBeVisible()
  })

  test('clicking "Start Session" opens the Start New Session dialog', async ({ page }) => {
    await page.goto('/sessions')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await page.getByRole('button', { name: 'Start Session' }).click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Start New Session' })).toBeVisible()
  })

  test('Start Session dialog has Machine selector, Command input, and Working Directory input', async ({ page }) => {
    await page.goto('/sessions')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await page.getByRole('button', { name: 'Start Session' }).click()
    // Labels from StartSessionDialog.tsx
    await expect(page.getByLabel('Machine')).toBeVisible()
    await expect(page.getByLabel('Command')).toBeVisible()
    // "Working Directory (optional)" uses a label that starts with "Working Directory"
    await expect(page.getByText(/Working Directory/i)).toBeVisible()
  })

  test('Start Session dialog can be cancelled', async ({ page }) => {
    await page.goto('/sessions')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await page.getByRole('button', { name: 'Start Session' }).click()
    await page.getByRole('button', { name: 'Cancel' }).click()
    await expect(page.getByRole('dialog')).not.toBeVisible()
  })

  test.skip('session detail page loads with terminal for a running session', async ({ page }) => {
    // Requires a running session ID.
    // Navigate to /sessions/<id>
    // await expect(page.locator('.xterm')).toBeVisible()  // xterm.js terminal element
    // await expect(page.getByText('Machine')).toBeVisible()  // meta card
    // await expect(page.getByText('Duration')).toBeVisible()
  })
})

// ─── Settings page ────────────────────────────────────────────────────────────

test.describe('Settings page — profile', () => {
  test('loads "Settings" heading and "Profile" card', async ({ page }) => {
    await page.goto('/settings')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await expect(page.getByRole('heading', { name: 'Settings' })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Profile' })).toBeVisible()
  })

  test('profile form has Full Name and Email Address inputs', async ({ page }) => {
    await page.goto('/settings')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await expect(page.getByLabel('Full Name')).toBeVisible()
    await expect(page.getByLabel('Email Address')).toBeVisible()
    await expect(page.getByRole('button', { name: 'Save Changes' })).toBeVisible()
  })

  test('password change form is present', async ({ page }) => {
    await page.goto('/settings')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await expect(page.getByRole('heading', { name: 'Password' })).toBeVisible()
    await expect(page.getByLabel('Current Password')).toBeVisible()
    await expect(page.getByLabel('New Password')).toBeVisible()
    await expect(page.getByLabel('Confirm New Password')).toBeVisible()
    await expect(page.getByRole('button', { name: 'Update Password' })).toBeVisible()
  })

  test('Notifications card is present', async ({ page }) => {
    await page.goto('/settings')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await expect(page.getByRole('heading', { name: 'Notifications' })).toBeVisible()
    await expect(page.getByText('Session crashed')).toBeVisible()
    await expect(page.getByText('Machine offline')).toBeVisible()
  })

  test('Danger Zone card with "Delete Account" button is present', async ({ page }) => {
    await page.goto('/settings')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await expect(page.getByText('Danger Zone')).toBeVisible()
    await expect(page.getByRole('button', { name: 'Delete Account' })).toBeVisible()
  })
})

test.describe('Settings page — org settings', () => {
  test('loads "Organization Settings" heading', async ({ page }) => {
    await page.goto('/settings/org')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await expect(page.getByRole('heading', { name: 'Organization Settings' })).toBeVisible()
  })

  test('URL slug input shows "app.sessionforge.io/" prefix', async ({ page }) => {
    await page.goto('/settings/org')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    // The static prefix text is rendered as a span adjacent to the slug input
    await expect(page.getByText('app.sessionforge.io/')).toBeVisible()
    await expect(page.getByLabel('URL Slug')).toBeVisible()
  })

  test('Team Members card with "Invite Member" button is visible', async ({ page }) => {
    await page.goto('/settings/org')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await expect(page.getByRole('heading', { name: 'Team Members' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Invite Member' })).toBeVisible()
  })

  test('Plan & Billing section shows all four plan names', async ({ page }) => {
    await page.goto('/settings/org')
    if (isLoginRedirect(page.url())) {
      test.skip(true, 'Requires authenticated session')
      return
    }
    await expect(page.getByText('Plan & Billing')).toBeVisible()
    // Four plan cards: Free, Pro, Team, Enterprise
    await expect(page.getByText('Free').first()).toBeVisible()
    await expect(page.getByText('Pro').first()).toBeVisible()
    await expect(page.getByText('Team').first()).toBeVisible()
    await expect(page.getByText('Enterprise').first()).toBeVisible()
  })
})
