version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: sessionforge
    main: ./cmd/sessionforge
    binary: sessionforge
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.BuildDate={{.Date}}
      - -X main.GitCommit={{.Commit}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: "sessionforge_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: sessionforge
    name: agent

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
