version: 2

before:
  hooks:
    - go mod tidy
    - go vet ./...

builds:
  - id: sessionforge
    main: ./cmd/sessionforge
    binary: sessionforge
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.BuildDate={{.Date}}
      - -X main.GitCommit={{.Commit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    format: tar.gz
    name_template: "sessionforge_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: PerryB-GIT
    name: sessionforge
  draft: false
  prerelease: auto
  name_template: "SessionForge Agent {{.Tag}}"
  header: |
    ## SessionForge Agent {{.Tag}}

    Download the appropriate binary for your platform below, or use the one-liner installer:

    **Linux / macOS:**
    ```sh
    curl -sSL https://raw.githubusercontent.com/PerryB-GIT/sessionforge/main/agent/scripts/install.sh | sh
    ```

    **Windows:**
    ```powershell
    irm https://raw.githubusercontent.com/PerryB-GIT/sessionforge/main/agent/scripts/install.ps1 | iex
    ```

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch
